### ISSUE TITLE
ImportError: No module named HamShieldPy

### ISSUE THREAD

**Issue by Temtel** [EnhancedRadioDevices/HamShieldPy#3]
Unable to run any of the examples.  Everything installed just fine, but I'm getting this:
`pi@pcrasp:~/src/HamShieldPy/examples $ python HandyTalkie.py
Traceback (most recent call last):
  File "HandyTalkie.py", line 42, in <module>
    from HamShieldPy import HamShield
ImportError: No module named HamShieldPy
`

**Comment by mogar** [comment]
Sorry about that. Can you please pull from master and try installing again? We pushed a few changes that *should* fix the issue now.

You may also have to run "sudo pip install wiringpi", which wasn't in the instructions until today.

**Comment by MrODonnell** [comment]
This did not work for me.  I am still getting that error message.  If it helps you, when I comment out the problematic import statement, I get an additional error on wiringpi import.

**Comment by mogar** [comment]
I used PiBakery to flash a new SD card, then ran through our instructions. Things seem to be working for me. Two questions for you:

1. Did you follow the pre-req installation instructions on our README?
2. Can you paste your exact error message (without commenting anything out in the example)?

**Comment by Temtel** [comment]
Finally got back around to testing again on a fresh install.  It worked.  
Oh, a couple of things:
1. I did an apt update and apt upgrade before installing HamshieldPy.  
2. wiringPi was already installed, but SWIG was not.

Thanks for all you do!
